<?xml version="1.0" encoding="utf-8"?><Database Name="Student_Management" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-DMO5JL19\THAITRINH;Initial Catalog=Student_Management;Persist Security Info=True;User ID=sa" SettingsObjectName="student_management.Properties.Settings" SettingsPropertyName="Student_ManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Attendance" Member="Attendances">
    <Type Name="Attendance">
      <Column Name="id" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="schedule_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="student_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="attended" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Student_Attendance" Member="Student" ThisKey="student_code" OtherKey="code" Type="Student" IsForeignKey="true" />
      <Association Name="Schedule_Attendance" Member="Schedule" ThisKey="schedule_id" OtherKey="id" Type="Schedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Class_Class_Student" Member="Class_Students" ThisKey="id" OtherKey="class_id" Type="Class_Student" />
      <Association Name="Class_Schedule" Member="Schedules" ThisKey="id" OtherKey="class_id" Type="Schedule" />
      <Association Name="Class_Class_Teacher" Member="Class_Teachers" ThisKey="id" OtherKey="class_id" Type="Class_Teacher" />
    </Type>
  </Table>
  <Table Name="dbo.Class_Student" Member="Class_Students">
    <Type Name="Class_Student">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="student_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Class_Class_Student" Member="Class" ThisKey="class_id" OtherKey="id" Type="Class" IsForeignKey="true" />
      <Association Name="Student_Class_Student" Member="Student" ThisKey="student_code" OtherKey="code" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Building" Member="Buildings">
    <Type Name="Building">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Building_Location" Member="Locations" ThisKey="id" OtherKey="building_id" Type="Location" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Teacher_Schedule" Member="Schedules" ThisKey="code" OtherKey="teacher_code" Type="Schedule" />
      <Association Name="Teacher_Class_Teacher" Member="Class_Teachers" ThisKey="code" OtherKey="teacher_code" Type="Class_Teacher" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subjects">
    <Type Name="Subject">
      <Column Name="code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="descript" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="weekly_session" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Subject_Schedule" Member="Schedules" ThisKey="code" OtherKey="subject_code" Type="Schedule" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Student_Attendance" Member="Attendances" ThisKey="code" OtherKey="student_code" Type="Attendance" />
      <Association Name="Student_Class_Student" Member="Class_Students" ThisKey="code" OtherKey="student_code" Type="Class_Student" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teacher_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="subject_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="slot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Schedule_Attendance" Member="Attendances" ThisKey="id" OtherKey="schedule_id" Type="Attendance" />
      <Association Name="Class_Schedule" Member="Class" ThisKey="class_id" OtherKey="id" Type="Class" IsForeignKey="true" />
      <Association Name="Subject_Schedule" Member="Subject" ThisKey="subject_code" OtherKey="code" Type="Subject" IsForeignKey="true" />
      <Association Name="Teacher_Schedule" Member="Teacher" ThisKey="teacher_code" OtherKey="code" Type="Teacher" IsForeignKey="true" />
      <Association Name="Location_Schedule" Member="Location" ThisKey="location_id" OtherKey="id" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="building_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="classroom_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Location_Schedule" Member="Schedules" ThisKey="id" OtherKey="location_id" Type="Schedule" />
      <Association Name="Building_Location" Member="Building" ThisKey="building_id" OtherKey="id" Type="Building" IsForeignKey="true" />
      <Association Name="Classroom_Location" Member="Classroom" ThisKey="classroom_id" OtherKey="id" Type="Classroom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Classroom" Member="Classrooms">
    <Type Name="Classroom">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Classroom_Location" Member="Locations" ThisKey="id" OtherKey="classroom_id" Type="Location" />
    </Type>
  </Table>
  <Table Name="dbo.Class_Teacher" Member="Class_Teachers">
    <Type Name="Class_Teacher">
      <Column Name="class_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teacher_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Class_Class_Teacher" Member="Class" ThisKey="class_id" OtherKey="id" Type="Class" IsForeignKey="true" />
      <Association Name="Teacher_Class_Teacher" Member="Teacher" ThisKey="teacher_code" OtherKey="code" Type="Teacher" IsForeignKey="true" />
    </Type>
  </Table>
</Database>